language: "perl"

os:
    - linux
    - osx

sudo: false

fast_finish: true

install: "echo"

script: "perl Configure.pl $RAKUDO_OPTIONS; make test"

branches:
   only:
     - nom
     - /smoke-me/

notifications:
  irc:
    channels:
      - "irc.freenode.net#p6dev"
    on_success: change
    on_failure: always
    template:
      - "Rakudo build %{result}. %{author} '%{commit_message}'"
      - "%{build_url} %{compare_url}"

env:
    - RAKUDO_OPTIONS="--backends=moar --gen-nqp        --gen-moar        --make-install"
    - RAKUDO_OPTIONS="--backends=moar --gen-nqp=master --gen-moar        --make-install"
    - RAKUDO_OPTIONS="--backends=moar --gen-nqp=master --gen-moar=master --make-install"
    - RAKUDO_OPTIONS="--backends=jvm  --gen-nqp                          --make-install"
    - RAKUDO_OPTIONS="--backends=jvm  --gen-nqp=master                   --make-install"
matrix:
  allow_failures:
    - env: RAKUDO_OPTIONS="--backends=jvm  --gen-nqp                          --make-install"
    - env: RAKUDO_OPTIONS="--backends=jvm  --gen-nqp=master                   --make-install"
